export enum EAct {
    VIEW = 0,
    CREATE = 1,
    READ = 2,
    UPDATE = 3,
    DELETE = 4,
    DOWNLOAD = 5,
    UPLOAD = 6,
    ACTION0 = 7,
    ACTION1 = 8,
    ACTION2 = 9,
    ACTION3 = 10,
    ACTION4 = 11,
    ACTION5 = 12,
    ACTION6 = 13,
    ACTION7 = 14,
    ALL = 15,
  }
  
  export enum PermissionsEnum {
    admin_permission = 'admin_permission',
    list_of_not_confirmed_alarms = 'list_of_not_confirmed_alarms',
    list_of_confirmed_alarms = 'list_of_confirmed_alarms',
    not_confirmed_alarm = 'not_confirmed_alarm',
    confirmed_alarm = 'confirmed_alarm',
    list_of_reports_in_work = 'list_of_reports_in_work',
    list_of_completed_reports = 'list_of_completed_reports',
    report_draft = 'report_draft',
    report_pending_approval = 'report_pending_approval',
    report_approved = 'report_approved',
    report_waiting_response = 'report_waiting_response',
    report_responded = 'report_responded',
    report_completed = 'report_completed',
    monitor = 'monitor',
    offline_detection_model_evaluation = 'offline_detection_model_evaluation',
    feature_correlation = 'feature_correlation',
    feature_importance = 'feature_importance',
    modeling = 'modeling',
    pid_selection = 'pid_selection',
    pid = 'pid',
    equipment = 'equipment',
    power_plant = 'power_plant',
    users = 'users',
    roles = 'roles',
  }
  